relationship_extraction:
  enabled: false  # Global flag for relationship extraction

model:
  provider: "groq"  # Options: "ollama", "gemini", "groq"
  rate_limits:
    ollama: 0  # seconds
    gemini: 5  # seconds
    groq: 5    # seconds
  models:
    ollama: "mistral:7b"
    gemini: "gemini-2.0-flash"
    groq: "qwen-2.5-32b"

document_stores:
  chroma:
    enabled: false
    supports_relationships: false
    settings:
      host: ${CHROMA_HOST}
      auth_token: ${CHROMA_AUTH_TOKEN}
      collection: ${CHROMA_COLLECTION}
      port: "443"
      ssl: true

  neo4j:
    enabled: false
    supports_relationships: true
    settings:
      uri: ${NEO4J_URI}
      user: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}
      database: ${NEO4J_DATABASE}

  age:
    enabled: false
    supports_relationships: true
    settings:
      host: ${AGE_HOST}
      port: ${AGE_PORT}
      database: ${AGE_DATABASE}
      user: ${AGE_USER}
      password: ${AGE_PASSWORD}

  memgraph:
    enabled: false
    supports_relationships: true
    settings:
      uri: ${MEMGRAPH_URI}
      user: ${MEMGRAPH_USER}
      password: ${MEMGRAPH_PASSWORD}

  pinecone:
    enabled: true
    supports_relationships: false
    settings:
      api_key: ${PINECONE_API_KEY}
      environment: ${PINECONE_ENVIRONMENT}
      index_name: ${PINECONE_INDEX}
      namespace: ${PINECONE_NAMESPACE}  # Optional, defaults to empty string if not set
