model:
  provider: "groq"  # Options: "ollama", "gemini", "groq"
  rate_limits:
    ollama: 0  # seconds
    gemini: 5  # seconds
    groq: 5    # seconds
  models:
    ollama: "mistral:7b"
    gemini: "gemini-2.0-flash"
    groq: "qwen-2.5-32b"

document_stores:
  chroma:
    enabled: false
    settings:
      host: ${CHROMA_HOST}
      auth_token: ${CHROMA_AUTH_TOKEN}
      collection: ${CHROMA_COLLECTION}
      port: "443"
      ssl: true

  neo4j:
    enabled: false
    settings:
      uri: ${NEO4J_URI}
      user: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}
      database: ${NEO4J_DATABASE}

  age:
    enabled: false
    settings:
      host: ${AGE_HOST}
      port: ${AGE_PORT}
      database: ${AGE_DATABASE}
      user: ${AGE_USER}
      password: ${AGE_PASSWORD}

  memgraph:
    enabled: true
    settings:
      uri: ${MEMGRAPH_URI}
      user: ${MEMGRAPH_USER}
      password: ${MEMGRAPH_PASSWORD}
