relationship_extraction:
  enabled: false  # Global flag for relationship extraction

model:
  provider: "groq"  # Options: "ollama", "gemini", "groq"
  rate_limits:
    ollama: 0  # seconds
    gemini: 5  # seconds
    groq: 5    # seconds
  models:
    ollama: "mistral:7b"
    gemini: "gemini-2.0-flash"
    groq: "qwen-2.5-32b" # deepseek-r1-distill-llama-70b ???

document_stores:
  pinecone:
    enabled: true
    supports_relationships: false
    settings:
      api_key: ${PINECONE_API_KEY}
      environment: ${PINECONE_ENVIRONMENT}
      index_name: ${PINECONE_INDEX}
      namespace: ${PINECONE_NAMESPACE}  # Optional, defaults to empty string if not set
