name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install development dependencies
        run: |
          uv pip install --system black mypy pytest pytest-cov types-requests

      - name: Install project dependencies
        run: |
          uv pip install --system -e .

      - name: Check formatting with Black
        run: black --check src

      - name: Type checking with MyPy
        run: mypy src

      - name: Run tests with pytest
        run: pytest -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
